# Change baseurl before deploy
baseurl = "https://gabrielabarrence.github.io/"
locale  = "pt-br"
title   = "Gabriela Barrence"

# Theme i18n support
# See all available values at https://github.com/CaiJimmy/hugo-theme-stack/tree/master/i18n
defaultContentLanguage = "pt-br"

# Set hasCJKLanguage to true if DefaultContentLanguage is in [zh-cn ja ko]
# This will make .Summary and .WordCount behave correctly for CJK languages.
hasCJKLanguage = false

# Change it to your Disqus shortname before using
# disqusShortname = "gabrielabarrence"

[pagination]
    pagerSize = 5
